<?php

$enlace = mysqli_connect("irmaemp.dx.am", "3217706_db", "K2+pachun", "irmaemp");

if (!$enlace) {
    echo "<br>Error: No se pudo conectar a MySQL.<br>";
    exit;
}


$folio = "SOCSEGURIDADDELNORTESA CONSTRUCTORAFENIXSOCIEDADANONIMA EMILIANOSANTIAGOVASQUEZRETAMAL ALEJANDROANTONIOMALDONADOCORDOVA SOUTHMARINEOVERSEASINC SOCOSCARCARRERAYCOMPANIALIMITADA CONSTRUCTORARIOMAULELIMITADA ALVAROPIOLOPEZFUENTES MILTONDAVIDPATINOROJAS EMPRESADEEXPLOTACIONDEPERTENENCIASMINERAS,TRATAMIENTODEMATERI ALDEBARANSERVICIOSDEINGENIERIAYCONSTRUCCIONSPA READYMIXHORMIGONESLIMITADA ASOCIACIONGREMIALDELTRANSPORTEDECARGAPORCARRETERAYAFINES GEPINGENIERÃASPA SKYAIRLINESA SKYAIRLINESA ARIACHASPA ARIACHASPA SOCIEDADAGRICOLACOMERCIALVALLENUEVOLIMITADA AGRICOLALAPAMPASPA EUSEBIOSEGUNDOCARVAJALCANTO CONSTRUCCIONESERIKCORDOVAESPINOZAE.I.R.L. TRANSPORTESPERICHYVILLALOBOSLIMITADA SEMILLASTUNICHELIMITADA SEMILLASTUNICHELIMITADA CONSORCIOEMBALSECHIRONTAS.A. MAQUINARIASINDUSTRIALESBRSPA PROARISPA PROARISPA PROARISPA CONSTRUCTORAMAGALIMITADA CONSTRUCTORAMAGALIMITADA CONSTRUCTORAMAGALIMITADA CONSTRUCTORAMAGALIMITADA CONSTRUCTORAMAGALIMITADA CONSTRUCTORAPACALSA SANFELIPESA";
$fechas = "22-04-2021 23-04-2021 23-04-2021 23-04-2021 23-04-2021 23-04-2021 27-04-2021 27-04-2021 27-04-2021 27-04-2021 27-04-2021 28-04-2021 28-04-2021 28-04-2021 30-04-2021 30-04-2021 30-04-2021 30-04-2021";
$arr = array('(UPDATE `facturacion` SET `FACT_NOMBRERS`="SOC SEGURIDAD DEL NORTE S A" WHERE `FACT_CODIGO`="472")',
'(UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA FENIX SOCIEDAD ANONIMA" WHERE `FACT_CODIGO`="473")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="EMILIANO SANTIAGO VASQUEZ RETAMAL" WHERE `FACT_CODIGO`="474")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="ALEJANDRO ANTONIO MALDONADO CORDOVA" WHERE `FACT_CODIGO`="475")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SOUTH MARINE OVERSEAS INC" WHERE `FACT_CODIGO`="476")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SOC OSCAR CARRERA Y COMPANIA LIMITADA" WHERE `FACT_CODIGO`="477")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA RIO MAULE LIMITADA" WHERE `FACT_CODIGO`="478")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="ALVARO PIO LOPEZ FUENTES" WHERE `FACT_CODIGO`="479")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="MILTON DAVID PATINO ROJAS" WHERE `FACT_CODIGO`="480")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="EMPRESA DE EXPLOTACION DE PERTENENCIAS MINERAS,TRATAMIENTO DE MATERI" WHERE `FACT_CODIGO`="481")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="ALDEBARAN SERVICIOS DE INGENIERIA Y CONSTRUCCION SPA" WHERE `FACT_CODIGO`="482")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="READY MIX HORMIGONES LIMITADA" WHERE `FACT_CODIGO`="483")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="ASOCIACION GREMIAL DEL TRANSPORTE DE CARGAPOR CARRETERA Y AFINES" WHERE `FACT_CODIGO`="484")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="GEP INGENIERÃA SPA" WHERE `FACT_CODIGO`="485")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SKY AIRLINE S A" WHERE `FACT_CODIGO`="486")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SKY AIRLINE S A" WHERE `FACT_CODIGO`="487")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="ARI ACHA SPA" WHERE `FACT_CODIGO`="488")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="ARI ACHA SPA" WHERE `FACT_CODIGO`="489")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SOCIEDAD AGRICOLA COMERCIAL VALLE NUEVO LIMITADA" WHERE `FACT_CODIGO`="490")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="AGRICOLA LA PAMPA SPA" WHERE `FACT_CODIGO`="491")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="EUSEBIO SEGUNDO CARVAJAL CANTO" WHERE `FACT_CODIGO`="492")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCCIONES ERIK CORDOVA ESPINOZA E.I.R.L." WHERE `FACT_CODIGO`="493")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="TRANSPORTES PERICH Y VILLA LOBOS LIMITADA" WHERE `FACT_CODIGO`="494")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SEMILLAS TUNICHE LIMITADA" WHERE `FACT_CODIGO`="495")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SEMILLAS TUNICHE LIMITADA" WHERE `FACT_CODIGO`="496")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSORCIO EMBALSE CHIRONTAS.A." WHERE `FACT_CODIGO`="497")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="MAQUINARIAS INDUSTRIALES BR SPA" WHERE `FACT_CODIGO`="498")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="PROARI SPA" WHERE `FACT_CODIGO`="499")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="PROARI SPA" WHERE `FACT_CODIGO`="500")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="PROARI SPA" WHERE `FACT_CODIGO`="501")',
'(((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA MAGA LIMITADA" WHERE `FACT_CODIGO`="502")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA MAGA LIMITADA" WHERE `FACT_CODIGO`="503")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA MAGA LIMITADA" WHERE `FACT_CODIGO`="504")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA MAGA LIMITADA" WHERE `FACT_CODIGO`="505")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA MAGA LIMITADA" WHERE `FACT_CODIGO`="506")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="CONSTRUCTORA PACAL SA" WHERE `FACT_CODIGO`="507")',
'((UPDATE `facturacion` SET `FACT_NOMBRERS`="SAN FELIPE SA" WHERE `FACT_CODIGO`="508")');

$facturanumero=472;

$texto="";
for($i=0; $i<count($arr);$i++){
    $texto = $arr[$i];
    $result = $enlace->query($texto);
}

?>